"""add_ranking_column_to_products

Revision ID: 249e1f92d7fe
Revises: ebdba1550ecc
Create Date: 2025-10-27 17:19:49.254540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249e1f92d7fe'
down_revision = 'ebdba1550ecc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('ranking', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'ranking')
    op.create_table('organizations',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('auth_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('organizations_pkey')),
    sa.UniqueConstraint('auth_token', name=op.f('organizations_auth_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
