"""add price_of_purxhase

Revision ID: 2db08d31b570
Revises: 3fa52ca77d79
Create Date: 2025-10-29 21:46:11.810360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2db08d31b570'
down_revision = '3fa52ca77d79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('price_of_purchase', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'price_of_purchase')
    # ### end Alembic commands ###
