"""Remove Buyer.name

Revision ID: 393dd1065a9f
Revises: 85268de402aa
Create Date: 2025-10-29 17:18:25.837155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '393dd1065a9f'
down_revision = '85268de402aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sellers', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
