"""Add auth tokens and buyer table

Revision ID: 4ae0691e63d5
Revises: 132dced05277
Create Date: 2025-10-27 11:34:19.232305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ae0691e63d5'
down_revision = '132dced05277'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('auth_token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_token')
    )
    op.add_column('sellers', sa.Column('auth_token', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'sellers', ['auth_token'])
    op.add_column('purchases', sa.Column('buyer_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'purchases', 'buyers', ['buyer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_column('purchases', 'buyer_id')
    op.drop_constraint(None, 'sellers', type_='unique')
    op.drop_column('sellers', 'auth_token')
    op.drop_table('buyers')
    # ### end Alembic commands ###
