"""add_product_images_association_table

Revision ID: 85268de402aa
Revises: bfa4782aa6f2
Create Date: 2025-10-29 11:25:04.101533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85268de402aa'
down_revision = 'bfa4782aa6f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_images',
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'image_id')
    )
    op.drop_constraint(op.f('products_image_id_fkey'), 'products', type_='foreignkey')
    op.drop_column('products', 'image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('products_image_id_fkey'), 'products', 'images', ['image_id'], ['id'])
    op.drop_table('product_images')
    # ### end Alembic commands ###
