"""Add rounds column

Revision ID: 8910042dc77d
Revises: 88bb53bc0a70
Create Date: 2025-10-31 20:05:01.840818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8910042dc77d'
down_revision = '88bb53bc0a70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('round', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'round')
    # ### end Alembic commands ###
