"""add_product_number_to_images

Revision ID: bfa4782aa6f2
Revises: 5b7c8d9e10f6
Create Date: 2025-10-29 10:31:51.774665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfa4782aa6f2'
down_revision = '5b7c8d9e10f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('product_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'product_number')
    # ### end Alembic commands ###
