"""Rename Sellers to Sellers

Revision ID: ebdba1550ecc
Revises: 4ae0691e63d5
Create Date: 2025-10-27 16:12:00.623324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebdba1550ecc'
down_revision = '4ae0691e63d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sellers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('auth_token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_token')
    )
    op.drop_table('sellers')
    op.add_column('products', sa.Column('seller_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('products_seller_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'sellers', ['seller_id'], ['id'])
    op.drop_column('products', 'seller_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('seller_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_seller_id_fkey'), 'products', 'sellers', ['seller_id'], ['id'])
    op.drop_column('products', 'seller_id')
    op.create_table('sellers',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('auth_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('sellers_pkey')),
    sa.UniqueConstraint('auth_token', name=op.f('sellers_auth_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('sellers')
    # ### end Alembic commands ###
