"""Change purchased_at from DateTime to Integer

Revision ID: f673f1ed3fc4
Revises: 249e1f92d7fe
Create Date: 2025-10-27 17:56:40.229350

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f673f1ed3fc4'
down_revision = '249e1f92d7fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First, delete all existing purchase data since we can't meaningfully convert timestamps to day numbers
    op.execute('DELETE FROM purchases')
    
    # Now alter the column type using raw SQL with USING clause
    op.execute('ALTER TABLE purchases ALTER COLUMN purchased_at TYPE INTEGER USING 0')
    op.execute('ALTER TABLE purchases ALTER COLUMN purchased_at SET NOT NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchases', 'purchased_at',
               existing_type=sa.Integer(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
